site_name: mbed Porting Guide

docs_dir: Docs

pages:
- ['index.md','mbed Porting Guide']
- ['mbed_OS.md','mbed OS', 'Porting mbed OS']
- ['HAL/HAL_intro.md','HAL','Porting the hardware abstraction layer']
- ['HAL/low_power_ticker.md','HAL','Low power ticker']
- ['uVisor/uVisor.md','mbed OS uVisor','uVisor']
- ['Add_Comp/mbed_client.md','Additional components','mbed Client']
- ['Add_Comp/6lowpan.md','Additional components','The mbed 6LoWPAN stack']

extra_css: ['FullCSS.css']
