site_name: Porting Guides

docs_dir: Docs

pages:
- ['index.md','Introduction to the porting guides']
- ['HAL/HAL_intro.md','HAL','Porting the hardware abstraction layer']
- ['HAL/low_power_ticker.md','HAL','Low power ticker']
- ['uVisor.md','mbed OS uVisor','uVisor']
- ['mbed_client.md','Additional components','mbed Client']
- ['6lowpan.md','Additional components','The mbed 6LoWPAN stack']

extra_css: ['FullCSS.css']
