site_name: Porting Guides

docs_dir: Docs

pages:
- ['index.md','Introduction to the porting guides']
- ['low_power_ticker.md','HAL','Low power ticker']
- ['uVisor.md','mbed OS uVisor','uVisor']

extra_css: ['FullCSS.css']
